name: Solar System Workflow

on:
  push:  
  workflow_dispatch:


env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}     

jobs:

    dev-deploy:
      #if: contains(github.ref, 'feature/')
      #needs: docker
      uses: ./.github/workflows/reuse-deployment.yml