name: Testing Mayank Github Actions

on: 
    push: 

jobs: 
    first: 
        name: List all files
        runs-on:  ubuntu-latest
        steps: 
        - name: Listing All Files
          run:  ls
        - name: Reading Index file
          run: cat index.html

