name: Deployment - Reusable Workflow

on:
    workflow_call: 
  
jobs:
    reuse-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: listing
              run: ls -la